name: Persist Progress Logs
description: Commit progress logs, falling back to artifact upload when pushes fail.
inputs:
  path:
    description: Newline-separated list of log files to persist.
    required: true
  commit-message:
    description: Commit message to use when pushing logs.
    default: chore: persist automation log
  artifact-label:
    description: Human-readable label used to build the artifact name when git push fails.
    default: progress-log
  retention-days:
    description: Artifact retention in days when fallback is required.
    default: '90'
runs:
  using: composite
  steps:
    - name: Stage log files
      shell: bash
      env:
        LOG_PATHS: ${{ inputs.path }}
      run: |
        set -euo pipefail
        if [ -z "$LOG_PATHS" ]; then
          echo "No log paths provided" >&2
          exit 1
        fi
        IFS=$'\n'
        for file in $LOG_PATHS; do
          if [ -z "$file" ]; then
            continue
          fi
          if [ ! -e "$file" ]; then
            echo "Missing log file: $file" >&2
            exit 1
          fi
          git add "$file"
        done

    - name: Commit log files
      id: git_commit
      shell: bash
      continue-on-error: true
      env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: |
        set -euo pipefail
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if git diff --cached --quiet; then
          echo "no_changes=true" >> "$GITHUB_OUTPUT"
          echo "pushed=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if git commit -m "$COMMIT_MESSAGE"; then
          if git push; then
            echo "pushed=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        fi
        echo "pushed=false" >> "$GITHUB_OUTPUT"
        exit 1

    - name: Prepare fallback artifact
      if: steps.git_commit.outputs.pushed != 'true' && steps.git_commit.outputs.no_changes != 'true'
      id: artifact
      shell: bash
      env:
        LOG_PATHS: ${{ inputs.path }}
        LABEL: ${{ inputs.artifact-label }}
      run: |
        set -euo pipefail
        node scripts/logs/archive.mjs --files "$LOG_PATHS" --label "$LABEL" >> "$GITHUB_OUTPUT"

    - name: Upload fallback artifact
      if: steps.git_commit.outputs.pushed != 'true' && steps.git_commit.outputs.no_changes != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact.outputs.artifact_name }}
        path: ${{ steps.artifact.outputs.artifact_path }}
        retention-days: ${{ inputs.retention-days }}
